name: Build and validate go-esi

on:
  - pull_request
  - push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Run tests
        run: go test -v ./...
      -
        name: Run writer tests
        run: go test -v ./writer

  build-caddy-middleware:
    name: Build and test Caddy middleware
    runs-on: ubuntu-latest
    steps:
      -
        name: Add domain.com host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 domain.com" | sudo tee -a /etc/hosts
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      -
        name: Build go-esi as caddy module
        run: |
          cd middleware/caddy
          xcaddy build --with github.com/sc0rp10/go-esi=../..
          go test -v ./...
